name: terraformmodule

on:
  push:
    branches: 
      - $default-branch
  pull_request:

jobs:
  terraformmodule:
    uses: dexcomit/github-workflows/.github/workflows/terraformmodule.yml@master
    secrets: inherit
