name: java-component-build

on:
  push:
    branches:
      - $default-branch

jobs:
  build:
    uses: dexcomit/github-workflows/.github/workflows/java-component-build.yml@master
    with:
      componentName: it-procurementbill
      componentBaseVersion: 1.0.0
      #gradle-version: 5.6.4
      #java-version: 11
