name: dexcom-javarelease-ci

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [Organization self-hosted, linux, x64]
    steps:
      - uses: dexcomit/github-workflows/.github/workflows/java-release@master
        with:
          componentName: it-procurementbill
          componentBaseVersion: 1.0.0
          #gradle-version: 5.6.4
          #java-version: 11
