name: cloudrun

on:
  pull_request:
    branches:
  push:
    branches:
      - $default-branch

jobs:
  cloudrun:
    uses: dexcomit/github-workflows/.github/workflows/cloudrun.yml@master
    with:
      App: subscriptions-us-west2
      Purpose: ecom
      Region:us-west2
      DbInstanceName: it-ecom-eu-dv-e19d41da:europe-west3:it-ecom-eu-dv-e19d41da
      ServiceAccount: subscriptions-europe-west3

      # ProdIT default
      #WorkloadIdentityServiceAccount: serverlessdeployer@pd-us-gcp-dvo-8q.iam.gserviceaccount.com
      #ProjectId: pd-us-gcp-dvo-8q
      #VpcProjectId: pd-us-gcp-dvo-8q

      # example sharedvpc service project ecom
      #WorkloadIdentityServiceAccount: cloudrundeployer@p8-integrations.iam.gserviceaccount.com
      #ProjectId: it-ecom-eu-dv-d6da
      #VpcProjectId: dv-us-gcp-sharedvpc-8q

      #BuildProject: p8-integrations
      #WorkloadIdentityProvider: projects/50512564251/locations/global/workloadIdentityPools/dv-us-gcp-sharedvpc-8q-pool/providers/non-prod-gh-provider
