#Change the name here to the component name
name: dexcom-java-component-build-ci

on:
  push:
    branches: [ $default-branch ]
    paths-ignore:
      - 'harness-deploy/**'
      - 'README.md'
      - '.github/**'
      - '.gitignore'
      - 'deploy/**'
  workflow_dispatch:

jobs:
  build:
    name: Java Component Build
    uses: dexcomit/github-workflows/.github/workflows/java-component-build.yml@master
    secrets: inherit
    with:
      componentName: 'enter_component_name_here'
      componentBaseVersion: '1.0.0'
      #gradle-version: 5.6.4
      #java-version: 8
