name: gradle-java-jib

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [Organization self-hosted, linux, x64]
    steps:
      - uses: ../.github/workflows/java-component-build
        with:
          componentName: it-procurementbill
          componentBaseVersion: 1.0.0
          #gradle-version: 5.6.4
          #java-version: 11
