#Change the name here to the component name
name: dexcom-java-component-test-ci

on:
  push:
    branches-ignore: [ $default-branch ]
    paths-ignore:
      - 'harness-deploy/**'
      - 'README.md'
      - '.github/**'
      - '.gitignore'
      - 'deploy/**'
  workflow_dispatch:

jobs:
  test:
    name: Java Component Test
    uses: dexcomit/github-workflows/.github/workflows/java-component-tests.yml@master
    secrets: inherit
    with:
      componentName: 'enter_component_name_here'
      #gradle-version: 5.6.4
      #java-version: 8