name: dexcom-terraformworkspace-ci

on:
  pull_request:
    branches:
      - $default-branch
  push:
    branches:
      - $default-branch

jobs:
  build:
    steps:
      - uses:  dexcomit/.github/.github/workflows/terraformworkspace.yml@master
