name: terraformworkspace

on:
  push:
    branches:
      - $default-branch
  pull_request:

jobs:
  terraformworkspace:
    uses: dexcomit/github-workflows/.github/workflows/terraformworkspace.yml@master
