#Change the name here to the component name
name: dexcom-java-component-build-ci-integrations-2

on:
  push:
    branches: [ $default-branch ]
    # Edit the paths to contain the directory of the component and the directories for all of its dependencies in the repo.
    paths:
      - 'folder_name/**'
  workflow_dispatch:

jobs:
  build:
    name: Java Component Build
    uses: dexcomit/github-workflows/.github/workflows/java-component-build-integrations-2.yml@master
    secrets: inherit
    with:
      componentName: 'enter_component_name_here'
      imageName: 'enter_image_name_here'
      componentBaseVersion: '1.0.0'
      #gradle-version: 7.5.1
      #java-version: 17
