name: dexcom-java-component-test-ci

on:
  push:
    branches-ignore: [ $default-branch ]
    paths-ignore:
      - 'harness-deploy/**'
      - 'README.md'
      - '.github/**'
      - '.gitignore'

jobs:
  test:
    name: Java Component Test
    uses: dexcomit/github-workflows/.github/workflows/java-component-tests.yml@master
    with:
      componentName: 'it-jenkins-java-component-pipeline-experiment'
      componentBaseVersion: '3.0.0'
      #gradle-version: 5.6.4
      #java-version: 8