name: dexcom-java-component-build-ci

on:
  push:
    branches: [ $default-branch ]
    paths-ignore:
      - 'harness-deploy/**'
      - 'README.md'
      - '.github/**'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Java Component Build
    uses: dexcomit/github-workflows/.github/workflows/java-component-build.yml@master
    with:
      componentName: 'it-jenkins-java-component-pipeline-experiment'
      componentBaseVersion: '3.0.0'
      #gradle-version: 5.6.4
      #java-version: 8