name: dexcom-terraformworkspace-ci

on:
  pull_request:
    branches:
      - $default-branch
  push:
    branches:
      - $default-branch

jobs:
  terraformworkspace:
    uses: dexcomit/github-workflows/.github/workflows/terraformworkspace.yml@master
