name: "basic"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  always:
    name: basic
    runs-on: ubuntu-latest
    steps:
    - name: branchname
      uses: deepakputhraya/action-branch-name@master
      with:
        # https://stackoverflow.com/questions/19322669/regular-expression-for-a-jira-identifier
        regex: '((?<!([A-Z]{1,10})-?)[A-Z]+-\d+)' # Regex the branch should match. This example enforces grouping
        allowed_prefixes: 'bugfix,feature,release,hotfix' # All branches should start with the given prefix
        ignore: master,main,dev,prod # Ignore exactly matching branch names from convention
        min_length: 5 # Min length of the branch name

# TODO any other basic required 
