on:
  workflow_call:

jobs:
  terraform:
    runs-on: [self-hosted, linux, x64]
    name: "TerraformWorkspace"
    steps:
      - name: branchname
        uses: deepakputhraya/action-branch-name@master
        with:
          # https://stackoverflow.com/questions/19322669/regular-expression-for-a-jira-identifier
          regex: '((?<!([A-Z]{1,10})-?)[A-Z]+-\d+)' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'bugfix,feature,release,hotfix' # All branches should start with the given prefix
          ignore: master,dev,prod # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 40 # Max length of the branch name
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: |
          terraform init
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -no-color
